name: Main Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  # CI: Lint, Test & Coverage
  ci:
    uses: ./.github/workflows/lint.yml
    secrets: inherit

  deploy:
    needs: [ci]
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
