name: Deploy Street Lifting App
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened, closed]
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
